### ISSUE TITLE
Coredumps with Ubuntu 22.04

### ISSUE THREAD

**Issue by CHiPs44** [tuupola/hagl_sdl2#9]
After adaptations for HAGL 0.6.0, demo coredumps after displaying the 3 RGB bars demo for a second.

I tried to do old style printf debugging with no results.

See https://github.com/CHiPs44/hagl_sdl2/tree/chips44-update-1

**Comment by CHiPs44** [comment]
Commenting the `hagl_flush(backend)` call in `flush_callback()` make the demo work.

**Comment by CHiPs44** [comment]
A better solution is to comment/remove the `hagl_flush(backend);` in the main loop (and uncomment it in `flush_callback()`).

**Comment by tuupola** [comment]
Thanks! I will update the demo today.

**Comment by CHiPs44** [comment]
See PR #10
